### ISSUE TITLE
Branches targetting master should have to pass tests before being merged.

### ISSUE THREAD

**Issue by fredx30** [iver-wharf/wharf-web#40]
We should add a GH action that targets branches targetted at master such that the tests suite is run before PR merge is allowed.

**Comment by jilleJr** [comment]
Easier said than done as Angular tests require an instance of a browser. Maybe there are some templates out there we can snag for running Angular tests in GitHub Actions

**Comment by jilleJr** [comment]
Closing in favor of #84
