### ISSUE TITLE
Favorites gets reset when fails to load projects list

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-web#52]
## Background

We support marking projects as favorite and storing them in localStorage

To speed things up, once the page has loaded it will automatically select the favorites tab if you have any projects marked as favorite

If a project would be removed then it also needs to be removed from the favorites list in localStorage, so after all projects has been fetched then it removes those that are not in the list.

## Issue

For some reason it removes all projects if it fails to fetch the list of projects, such as when the wharf-api is down due to upgrade or other downtime.

I've read through the code and this shouldn't be happening according to me, but I'm obviously missing something. This needs investigation and a bugfix.

**Comment by jilleJr** [comment]
@Alexamakans you tried to replicate this and failed, right? If so then I'd say it's OK to close this as it cannot be reproduced. Possible that it was fixed in an unrelated PR or something

**Comment by Alexamakans** [comment]
> @Alexamakans you tried to replicate this and failed, right? If so then I'd say it's OK to close this as it cannot be reproduced. Possible that it was fixed in an unrelated PR or something

Yes, was unable to replicate.
